-- =============================================================================
-- 11. SEED DATA
-- =============================================================================
INSERT IGNORE INTO roles (name, display_name, hierarchy_level)
VALUES ('admin', 'Administrator', 10),
    ('contractor', 'Contractor', 1),
    ('khalasi', 'Khalasi', 1),
    ('je', 'Junior Engineer', 2),
    ('ae', 'Assistant Engineer', 3),
    ('aee', 'Asst. Executive Engineer', 4),
    ('ee', 'Executive Engineer', 5),
    ('se', 'Superintending Engineer', 6),
    ('addl_ce', 'Addl. Chief Engineer', 7),
    ('ce', 'Chief Engineer', 8),
    ('secretary', 'Secretary', 9),
    ('finance', 'Finance', 5),
    ('dc', 'DC', 9);
-- FIX: seed admin password placeholder — replace with a real bcrypt hash
--      generated by your application before deploying to any environment.
--      NEVER use a hardcoded or predictable hash in staging/production.
INSERT IGNORE INTO users (
        id,
        name,
        email,
        phone,
        role_id,
        status,
        password,
        is_verified
    )
SELECT 'usr_sys_admin',
    'System Admin',
    'admin@phe.app',
    '9999999999',
    r.id,
    'active',
    '$2b$12$REPLACE_THIS_WITH_A_REAL_BCRYPT_HASH_GENERATED_BY_THE_APP',
    TRUE
FROM roles r
WHERE r.name = 'admin';
INSERT IGNORE INTO breakdown_statuses (status, display_name)
VALUES ('reported', 'Reported'),
    ('pending', 'Pending Approval'),
    ('approved', 'Approved'),
    ('assigned', 'Assigned'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
    ('closed', 'Closed'),
    ('rejected', 'Rejected'),
    ('hold', 'On Hold');
-- Seed Permissions
INSERT IGNORE INTO permissions (permission_code, module, description)
VALUES (
        'manage_users',
        'users',
        'Can change user statuses, roles, and verification state'
    ),
    (
        'approve_breakdown',
        'breakdowns',
        'Can approve or reject breakdown reports'
    ),
    (
        'assign_contractor',
        'breakdowns',
        'Can assign contractors to breakdowns (EE only)'
    ),
    (
        'upload_stage_media',
        'media',
        'Can upload stage-wise repair photos/videos'
    ),
    (
        'issue_certificate',
        'breakdowns',
        'Can issue completion certificates'
    ),
    (
        'view_audit_logs',
        'audit',
        'Can view the full audit trail (Finance/DC)'
    ),
    (
        'manage_assets',
        'assets',
        'Can add/edit infrastructure asset records'
    );
-- Assign all permissions to admin
INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id,
    p.id
FROM roles r,
    permissions p
WHERE r.name = 'admin';
-- Seed Geographic Data
INSERT IGNORE INTO states (name, code)
VALUES ('Assam', 'AS');
SET @state_id = (
        SELECT id
        FROM states
        WHERE code = 'AS'
    );
INSERT IGNORE INTO districts (state_id, name)
VALUES (@state_id, 'Kamrup Metropolitan');
SET @district_id = (
        SELECT id
        FROM districts
        WHERE state_id = @state_id
            AND name = 'Kamrup Metropolitan'
    );
INSERT IGNORE INTO cities (district_id, name)
VALUES (@district_id, 'Guwahati');
SET @city_id = (
        SELECT id
        FROM cities
        WHERE district_id = @district_id
            AND name = 'Guwahati'
    );
INSERT IGNORE INTO pincodes (code, city_id, area_name)
VALUES ('781001', @city_id, 'Panbazar');
INSERT IGNORE INTO pincodes (code, city_id, area_name)
VALUES ('781005', @city_id, 'Bhangagarh');
INSERT IGNORE INTO pincodes (code, city_id, area_name)
VALUES ('781006', @city_id, 'Dispur');
-- =============================================================================
-- 4. Seed INFRASTRUCTURE HIERARCHY
-- =============================================================================
INSERT IGNORE INTO divisions (id, name, district_id, description)
VALUES (
        'div_ght2',
        'Guwahati Division No. II',
        @district_id,
        'Main Urban Division'
    );
INSERT IGNORE INTO water_intake_plants (
        id,
        division_id,
        name,
        capacity_mld,
        address_line
    )
VALUES (
        'brg_panbazar',
        'div_ght2',
        'Panbazar Intake Barge',
        20.0,
        'Brahmaputra River, Panbazar'
    );
-- 3 Production Centres
INSERT IGNORE INTO production_centres (id, intake_plant_id, name, capacity_mld, type)
VALUES (
        'pc_dispur',
        'brg_panbazar',
        'DISPUR WSS',
        12.7,
        'WSS'
    ),
    (
        'pc_gu_aec',
        'brg_panbazar',
        'GU & AEC WSS',
        4.5,
        'WSS'
    ),
    (
        'pc_sarusajai',
        'brg_panbazar',
        'SARUSAJAI WSS',
        3.0,
        'WSS'
    );
-- Water Treatment Plants
INSERT IGNORE INTO water_treatment_plants (id, centre_id, name, capacity_mld)
VALUES (
        'wtp_panbazar',
        'pc_dispur',
        'Panbazar WTP',
        12.7
    ),
    (
        'wtp_jalukbari',
        'pc_gu_aec',
        'Jalukbari WTP',
        4.5
    ),
    (
        'wtp_sarusajai',
        'pc_sarusajai',
        'Sarusajai WTP',
        3.0
    );
-- Boosting Stations
INSERT IGNORE INTO boosting_stations (id, wtp_id, name)
VALUES (
        'bst_bhangagarh',
        'wtp_panbazar',
        'Bhangagarh Boosting Station'
    ),
    (
        'bst_mla',
        'wtp_panbazar',
        'MLA Boosting Station'
    ),
    (
        'bst_capital',
        'wtp_panbazar',
        'Capital Boosting Station'
    ),
    (
        'bst_khanapara',
        'wtp_panbazar',
        'Khanapara Boosting Station'
    ),
    (
        'bst_health',
        'wtp_panbazar',
        'Hengrabari Health Complex Boosting Station'
    ),
    (
        'bst_colony',
        'wtp_panbazar',
        'Hengrabari Housing Colony Boosting Station'
    ),
    (
        'bst_kahilipara',
        'wtp_panbazar',
        'Kahilipara Boosting Station'
    ),
    (
        'bst_hudco',
        'wtp_panbazar',
        'HUDCO Boosting Station'
    ),
    (
        'bst_zoo',
        'wtp_panbazar',
        'State Zoo Boosting Station'
    ),
    (
        'bst_gmc_foot',
        'wtp_panbazar',
        'GMC Foot hill Boosting Station'
    ),
    (
        'bst_gmc_top',
        'wtp_panbazar',
        'GMC Top hill Boosting Station'
    ),
    (
        'bst_grade4',
        'wtp_panbazar',
        'Grade IV Boosting Station'
    ),
    (
        'bst_gu_foothill',
        'wtp_jalukbari',
        'GU Foothill Boosting Station'
    ),
    (
        'bst_sports_comp',
        'wtp_sarusajai',
        'Sarusajai Sports Complex Boosting Station'
    );
-- =============================================================================
-- 12. TRIGGERS (AUTOMATIC AUDITING)
-- =============================================================================
DELIMITER // -- Trigger: log user status changes into audit_logs
CREATE TRIGGER trg_audit_user_status
AFTER
UPDATE ON users FOR EACH ROW BEGIN IF OLD.status <> NEW.status THEN
INSERT INTO audit_logs (
        user_id,
        action_type,
        entity_type,
        entity_id,
        diff_json
    )
VALUES (
        NULL,
        -- logged as System; triggers don't have session user context
        'UPDATE_STATUS',
        'users',
        NEW.id,
        JSON_OBJECT(
            'old_status',
            OLD.status,
            'new_status',
            NEW.status
        )
    );
END IF;
END // -- Trigger: auto-populate repair_history when a completion certificate is issued
CREATE TRIGGER trg_populate_repair_history
AFTER
INSERT ON completion_certificates FOR EACH ROW BEGIN
DECLARE v_asset_id VARCHAR(30);
DECLARE v_asset_type ENUM('pipeline', 'component');
DECLARE v_asset_name VARCHAR(255);
DECLARE v_completion_at TIMESTAMP;
DECLARE v_contractor_id VARCHAR(30);
-- Fetch breakdown asset info and contractor
SELECT COALESCE(b.pipeline_id, b.component_unit_id),
    IF(
        b.pipeline_id IS NOT NULL,
        'pipeline',
        'component'
    ),
    b.completion_at,
    wo.contractor_id INTO v_asset_id,
    v_asset_type,
    v_completion_at,
    v_contractor_id
FROM breakdowns b
    LEFT JOIN work_orders wo ON wo.breakdown_id = b.id
WHERE b.id = NEW.breakdown_id
LIMIT 1;
-- Resolve asset name from the correct table
IF v_asset_type = 'pipeline' THEN
SELECT name INTO v_asset_name
FROM pipelines
WHERE id = v_asset_id;
ELSE -- For components, we fetch name from the parent component table via component_units
SELECT c.name INTO v_asset_name
FROM component_units cu
    JOIN components c ON cu.component_id = c.id
WHERE cu.id = v_asset_id;
END IF;
INSERT INTO repair_history (
        id,
        breakdown_id,
        certificate_id,
        asset_id,
        asset_type,
        asset_name,
        budget_allocated,
        repair_cost,
        contractor_id,
        completed_at,
        verified_by
    )
VALUES (
        CONCAT(
            'hist_',
            SUBSTRING(REPLACE(UUID(), '-', ''), 1, 16)
        ),
        NEW.breakdown_id,
        NEW.id,
        v_asset_id,
        v_asset_type,
        COALESCE(
            v_asset_name,
            CONCAT('[Deleted ', v_asset_type, ']')
        ),
        NEW.budget_allocated,
        NEW.repair_cost,
        v_contractor_id,
        COALESCE(v_completion_at, CURRENT_TIMESTAMP),
        NEW.issued_by
    );
END // DELIMITER;