import 'component_codes.dart';

class WtpComponent {
  final int id;
  final String category;
  final String slNo;
  final String name;
  final String quantity;
  final String locationUsage;
  final String maintenancePurpose;

  const WtpComponent({
    required this.id,
    required this.category,
    required this.slNo,
    required this.name,
    required this.quantity,
    required this.locationUsage,
    required this.maintenancePurpose,
  });

  String get shortCategory => ComponentCodes.getCategoryCode(category);
  String get shortName => ComponentCodes.getNameCode(name);
  String get shortLocation => ComponentCodes.getLocationCode(locationUsage);
}

const List<WtpComponent> wtpComponents = [
  WtpComponent(
    id: 1,
    category: "Machinery Components",
    slNo: "1",
    name: "Pumpset (125 HP)",
    quantity: "4",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Raw water pumping",
  ),
  WtpComponent(
    id: 2,
    category: "Machinery Components",
    slNo: "2",
    name: "Pumpset (100 HP)",
    quantity: "3",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Raw water pumping",
  ),
  WtpComponent(
    id: 3,
    category: "Machinery Components",
    slNo: "3",
    name: "Pumpset (80 HP)",
    quantity: "3",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Raw water pumping",
  ),
  WtpComponent(
    id: 4,
    category: "Machinery Components",
    slNo: "4",
    name: "Vacuum Pumpset (10 HP)",
    quantity: "2",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Priming and suction",
  ),
  WtpComponent(
    id: 5,
    category: "Machinery Components",
    slNo: "5",
    name: "Pumpset (125 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 6,
    category: "Machinery Components",
    slNo: "6",
    name: "Pumpset (100 HP)",
    quantity: "2",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 7,
    category: "Machinery Components",
    slNo: "7",
    name: "Pumpset (80 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 8,
    category: "Machinery Components",
    slNo: "8",
    name: "Back Washer Pumpset (30 Hp)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Back Washing",
  ),
  WtpComponent(
    id: 9,
    category: "Machinery Components",
    slNo: "9",
    name: "Pumpset (125 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 10,
    category: "Machinery Components",
    slNo: "10",
    name: "Pumpset (100 HP)",
    quantity: "4",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 11,
    category: "Machinery Components",
    slNo: "11",
    name: "Pumpset (80 HP)",
    quantity: "3",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Water supply",
  ),
  WtpComponent(
    id: 12,
    category: "Machinery Components",
    slNo: "12",
    name: "Vacuum Pumpset (10 HP)",
    quantity: "2",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Priming",
  ),
  WtpComponent(
    id: 13,
    category: "Machinery Components",
    slNo: "13",
    name: "Air Blower (20 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Aeration",
  ),
  WtpComponent(
    id: 14,
    category: "Machinery Components",
    slNo: "14",
    name: "OHR Pumpset (15 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Overhead tank filling",
  ),
  WtpComponent(
    id: 15,
    category: "Machinery Components",
    slNo: "15",
    name: "Pumpset (75 HP)",
    quantity: "3",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Distribution",
  ),
  WtpComponent(
    id: 16,
    category: "Machinery Components",
    slNo: "16",
    name: "Vacuum Pumpset (5 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Priming",
  ),
  WtpComponent(
    id: 17,
    category: "Machinery Components",
    slNo: "17",
    name: "Clarifier Scraper Pumpset (5 HP)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Clarification",
  ),
  WtpComponent(
    id: 18,
    category: "Machinery Components",
    slNo: "18",
    name: "DG Set (325 KVA)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Backup power",
  ),
  WtpComponent(
    id: 19,
    category: "Machinery Components",
    slNo: "19",
    name: "DG Set (325 KVA)",
    quantity: "1",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Backup power",
  ),
  WtpComponent(
    id: 20,
    category: "Machinery Components",
    slNo: "20",
    name: "Transformer (250 KVA)",
    quantity: "2",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Distributing electricity",
  ),
  WtpComponent(
    id: 21,
    category: "Machinery Components",
    slNo: "21",
    name: "Transformer (500 KVA)",
    quantity: "1",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Distributing electricity",
  ),
  WtpComponent(
    id: 1,
    category: "Mechanical Components",
    slNo: "1",
    name: "Barge Mechanical Structure",
    quantity: "",
    locationUsage: "River Brahmaputra",
    maintenancePurpose: "Raw water intake",
  ),
  WtpComponent(
    id: 2,
    category: "Mechanical Components",
    slNo: "2",
    name: "Screening Filter",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Separate suspended solids",
  ),
  WtpComponent(
    id: 3,
    category: "Mechanical Components",
    slNo: "3",
    name: "Flexible Hose Pipe (150 mm dia)",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Flow transfer",
  ),
  WtpComponent(
    id: 4,
    category: "Mechanical Components",
    slNo: "4",
    name: "Steel Ropes",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Hold Barge in position",
  ),
  WtpComponent(
    id: 5,
    category: "Mechanical Components",
    slNo: "5",
    name: "Fullway Valve (15 mm)",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Flow regulation",
  ),
  WtpComponent(
    id: 6,
    category: "Mechanical Components",
    slNo: "6",
    name: "Fullway Valve (20 mm)",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Flow regulation",
  ),
  WtpComponent(
    id: 7,
    category: "Mechanical Components",
    slNo: "7",
    name: "Sluice Valve (150 mm dia)",
    quantity: "13",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Flow control",
  ),
  WtpComponent(
    id: 8,
    category: "Mechanical Components",
    slNo: "8",
    name: "NRVs (Non-return valves)",
    quantity: "",
    locationUsage: "Panbazar Barge",
    maintenancePurpose: "Preventing water backflow",
  ),
  WtpComponent(
    id: 9,
    category: "Mechanical Components",
    slNo: "9",
    name: "Scraper Systems",
    quantity: "",
    locationUsage: "Treatment Plant",
    maintenancePurpose:
        "Bottom scraping (sludge removal) or Top skimming (scum/foam removal)",
  ),
  WtpComponent(
    id: 10,
    category: "Mechanical Components",
    slNo: "10",
    name: "Spindle (Filter spindle)",
    quantity: "12",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Valve operation",
  ),
  WtpComponent(
    id: 11,
    category: "Mechanical Components",
    slNo: "11",
    name: "Sluice Valve (150 mm dia)",
    quantity: "14",
    locationUsage: "Treatment Plant",
    maintenancePurpose: "Flow control",
  ),
  WtpComponent(
    id: 12,
    category: "Mechanical Components",
    slNo: "12",
    name: "NRVs (Non-return valves)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Preventing water backflow",
  ),
  WtpComponent(
    id: 13,
    category: "Mechanical Components",
    slNo: "13",
    name: "Air Valve",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Air release",
  ),
  WtpComponent(
    id: 14,
    category: "Mechanical Components",
    slNo: "14",
    name: "GI Nipple (15 mm)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Pipe joining",
  ),
  WtpComponent(
    id: 15,
    category: "Mechanical Components",
    slNo: "15",
    name: "GI Nipple (20 mm)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Pipe joining",
  ),
  WtpComponent(
    id: 16,
    category: "Mechanical Components",
    slNo: "16",
    name: "GI Union Socket",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Pipe connection",
  ),
  WtpComponent(
    id: 17,
    category: "Mechanical Components",
    slNo: "17",
    name: "Pipes (250 mm)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Water Flow",
  ),
  WtpComponent(
    id: 18,
    category: "Mechanical Components",
    slNo: "18",
    name: "Pipes (350 mm)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Water Flow",
  ),
  WtpComponent(
    id: 19,
    category: "Mechanical Components",
    slNo: "19",
    name: "Pipes (450 mm)",
    quantity: "",
    locationUsage: "Treatment Plant & Panbazar Barge",
    maintenancePurpose: "Water Flow",
  ),
  WtpComponent(
    id: 1,
    category: "Electrical Components",
    slNo: "1",
    name: "MCCB (Panel protection device)",
    quantity: "",
    locationUsage: "Electrical Panel",
    maintenancePurpose: "Circuit protection",
  ),
  WtpComponent(
    id: 2,
    category: "Electrical Components",
    slNo: "2",
    name: "MCB (Circuit breaker)",
    quantity: "",
    locationUsage: "Electrical Panel",
    maintenancePurpose: "Protection",
  ),
  WtpComponent(
    id: 3,
    category: "Electrical Components",
    slNo: "3",
    name: "Capacitor (Power factor correction)",
    quantity: "",
    locationUsage: "Electrical Panel",
    maintenancePurpose: "Voltage stability",
  ),
  WtpComponent(
    id: 4,
    category: "Electrical Components",
    slNo: "4",
    name: "Fuse Wire (HT fuse (40 Amp))",
    quantity: "",
    locationUsage: "Transformer",
    maintenancePurpose: "Protection",
  ),
  WtpComponent(
    id: 5,
    category: "Electrical Components",
    slNo: "5",
    name: "Barrel (HT Barrel)",
    quantity: "",
    locationUsage: "Transformer",
    maintenancePurpose: "Protection",
  ),
  WtpComponent(
    id: 6,
    category: "Electrical Components",
    slNo: "",
    name: "Switch (40 Amp)",
    quantity: "",
    locationUsage: "Transformer Control Pannel",
    maintenancePurpose: "Circuit protection",
  ),
  WtpComponent(
    id: 7,
    category: "Electrical Components",
    slNo: "6",
    name: "LED Bulb (Lighting)",
    quantity: "",
    locationUsage: "Plant & Barge",
    maintenancePurpose: "Illumination",
  ),
  WtpComponent(
    id: 8,
    category: "Electrical Components",
    slNo: "7",
    name: "Tube Light (Lighting)",
    quantity: "",
    locationUsage: "Plant & Barge",
    maintenancePurpose: "Illumination",
  ),
  WtpComponent(
    id: 9,
    category: "Electrical Components",
    slNo: "8",
    name: "Bulb Holder (Lighting fixture)",
    quantity: "",
    locationUsage: "Electrical system",
    maintenancePurpose: "Lighting support",
  ),
  WtpComponent(
    id: 10,
    category: "Electrical Components",
    slNo: "9",
    name: "Electrical Tape (Black tape)",
    quantity: "",
    locationUsage: "Electrical system",
    maintenancePurpose: "Insulation",
  ),
  WtpComponent(
    id: 1,
    category: "Chemical & Treatment Components",
    slNo: "1",
    name: "Alum (Ferric Alum)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "Coagulation",
  ),
  WtpComponent(
    id: 2,
    category: "Chemical & Treatment Components",
    slNo: "2",
    name: "Hydrated Lime (pH adjustment chemical)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "pH control",
  ),
  WtpComponent(
    id: 3,
    category: "Chemical & Treatment Components",
    slNo: "3",
    name: "Bleaching Powder (Chlorination chemical)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "Disinfection",
  ),
  WtpComponent(
    id: 1,
    category: "Consumables & Maintenance Materials",
    slNo: "1",
    name: "Gland Packing (12 mm, 10 mm)",
    quantity: "",
    locationUsage: "Pumps & valves",
    maintenancePurpose: "Seal leakage",
  ),
  WtpComponent(
    id: 2,
    category: "Consumables & Maintenance Materials",
    slNo: "2",
    name: "Nut & Bolt (Various sizes)",
    quantity: "",
    locationUsage: "Pumps & valves",
    maintenancePurpose: "Fastening",
  ),
  WtpComponent(
    id: 3,
    category: "Consumables & Maintenance Materials",
    slNo: "3",
    name: "Rubber Gasket (250 gm)",
    quantity: "",
    locationUsage: "Valves",
    maintenancePurpose: "Leak prevention",
  ),
  WtpComponent(
    id: 4,
    category: "Consumables & Maintenance Materials",
    slNo: "4",
    name: "Grease (Lubricant)",
    quantity: "",
    locationUsage: "Pumps",
    maintenancePurpose: "Reduce friction",
  ),
  WtpComponent(
    id: 5,
    category: "Consumables & Maintenance Materials",
    slNo: "5",
    name: "Cotton Waste (Cleaning material)",
    quantity: "",
    locationUsage: "Pumps",
    maintenancePurpose: "Cleaning",
  ),
  WtpComponent(
    id: 6,
    category: "Consumables & Maintenance Materials",
    slNo: "6",
    name: "Handwash (Hygiene material)",
    quantity: "",
    locationUsage: "Plant",
    maintenancePurpose: "Worker hygiene",
  ),
  WtpComponent(
    id: 7,
    category: "Consumables & Maintenance Materials",
    slNo: "7",
    name: "Teflon Tape (Sealant)",
    quantity: "",
    locationUsage: "Pipe joints",
    maintenancePurpose: "Leak prevention",
  ),
  WtpComponent(
    id: 8,
    category: "Consumables & Maintenance Materials",
    slNo: "8",
    name: "Hacksaw Blade (Cutting tool)",
    quantity: "",
    locationUsage: "Maintenance work",
    maintenancePurpose: "Cutting",
  ),
  WtpComponent(
    id: 9,
    category: "Consumables & Maintenance Materials",
    slNo: "9",
    name: "UPVC Solvent (Pipe adhesive)",
    quantity: "",
    locationUsage: "Pipe joints",
    maintenancePurpose: "Bonding",
  ),
  WtpComponent(
    id: 10,
    category: "Consumables & Maintenance Materials",
    slNo: "10",
    name: "M-Seal (Leak sealant)",
    quantity: "",
    locationUsage: "Pipe & tank",
    maintenancePurpose: "Repair",
  ),
  WtpComponent(
    id: 11,
    category: "Consumables & Maintenance Materials",
    slNo: "11",
    name: "Coconut Rope (Mechanical support)",
    quantity: "",
    locationUsage: "Barge",
    maintenancePurpose: "Structural support",
  ),
  WtpComponent(
    id: 12,
    category: "Consumables & Maintenance Materials",
    slNo: "12",
    name: "Filter Sand (Rapid sand filter media)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "Filtration",
  ),
  WtpComponent(
    id: 1,
    category: "Civil Components",
    slNo: "1",
    name: "Aerator (2 Nos)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 2,
    category: "Civil Components",
    slNo: "2",
    name: "Mixer",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 3,
    category: "Civil Components",
    slNo: "3",
    name: "Lime Doser",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 4,
    category: "Civil Components",
    slNo: "4",
    name: "Alum Doser",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 5,
    category: "Civil Components",
    slNo: "5",
    name: "Tube Shettler (0.5 lacs liters)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 6,
    category: "Civil Components",
    slNo: "6",
    name: "Floculator (4 lacs liters)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 7,
    category: "Civil Components",
    slNo: "7",
    name: "Clarifier Unit (12 lacs liters)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 8,
    category: "Civil Components",
    slNo: "8",
    name: "Sludge Pit",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 9,
    category: "Civil Components",
    slNo: "9",
    name: "Rapid Sand Filter (2 Nos)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 10,
    category: "Civil Components",
    slNo: "10",
    name: "Chlorinator",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
  WtpComponent(
    id: 11,
    category: "Civil Components",
    slNo: "11",
    name: "Water Reserviour (0.8 lacs liters & 2 lacs liters)",
    quantity: "",
    locationUsage: "Treatment plant",
    maintenancePurpose: "",
  ),
];

Map<String, List<WtpComponent>> get groupedWtpComponents {
  final map = <String, List<WtpComponent>>{};
  for (var c in wtpComponents) {
    if (!map.containsKey(c.category)) {
      map[c.category] = [];
    }
    map[c.category]!.add(c);
  }
  return map;
}

List<String> get wtpComponentCategories {
  return groupedWtpComponents.keys.toList();
}
